# Numpy（数值计算）

## 1. Numpy 基础

### 1.1 数组创建

#### 1.1.1 有效创建方式

In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(1, 10, 2)

In [5]:
a

array([1, 3, 5, 7, 9])

In [13]:
len(np.linspace(0, 10))

50

创建会包含尾巴的数组

In [11]:
np.linspace(0, 10, 2)

array([  0.,  10.])

In [18]:
np.linspace(0, 15, 16).reshape(4, 4)

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.]])

In [26]:
b = np.linspace(0, 7, 8).reshape(2, 4)
b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.]])

In [27]:
b.shape

(2, 4)

In [28]:
b = np.arange(0, 8).reshape(2, 2, 2)

In [29]:
b

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

查看维度

In [31]:
b.ndim

3

查找某项功能函数

In [10]:
# np.lookfor('create array')
# np.con*?

#### 1.1.2 其他创建

0，1 数组

In [32]:
np.zeros(1)

array([ 0.])

In [38]:
a = np.zeros((1, 2))
a

array([[ 0.,  0.]])

In [39]:
a.ndim

2

In [34]:
np.zeros(2)

array([ 0.,  0.])

In [41]:
b = np.ones((3, 3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [42]:
b.ndim

2

In [45]:
b = np.ones((3, 3, 3))
b.ndim

3

In [46]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [49]:
c = np.eye(5)
c

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [52]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
a = np.random.rand(4, 2)
a

array([[ 0.71363928,  0.30800873],
       [ 0.54273486,  0.67771969],
       [ 0.69759852,  0.34959487],
       [ 0.01168304,  0.21990915]])

In [59]:
np.random.seed(1234)
b = np.random.rand(4)

In [58]:
a

array([[ 0.71363928,  0.30800873],
       [ 0.54273486,  0.67771969],
       [ 0.69759852,  0.34959487],
       [ 0.01168304,  0.21990915]])

In [60]:
b

array([ 0.19151945,  0.62210877,  0.43772774,  0.78535858])